### ISSUE TITLE
Doesn't work well on some locale such as CJK.

### ISSUE THREAD

**Issue by MikuroXina** [chipto/pid-cwd#1]
I think because the exec(~) calling that getting cwd is not set the locale.
Why not you specify locale with environmental variable like "LANG=en_US.utf-8 lsof ~"?
In reference, my tested env is macOS 10.14.4 (Japanese).

**Comment by zikaari** [comment]
Can you please try that change and if it works, create a pull request? 

Thanks for reporting (and helping :)

**Comment by MikuroXina** [comment]
I've created #2 .
